# 🚧 Monkey-patch BEFORE react_native_pods.rb is required
module ReactNativePodsUtils
  def self.check_minimum_required_xcode
    Pod::UI.puts "[!] ⚠️ Skipping Xcode version check (requirement was >=16.1, found #{Pod::Executable.execute_command('xcodebuild', ['-version']).split("\n").first})".yellow
    return
  end
end

# Now require react_native_pods.rb
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip


platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'aviatorQuiz' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )
  end
end
